name: go-twitter-action
author: @devigned
description: Send a Tweet via an GitHub Action. See https://developer.twitter.com/en/portal/projects for details on how to setup and app.
inputs:
  message:
    description: 'message you want to tweet'
    required: true
  apiKey:
    description: 'api key for Twitter api'
    required: true
  apiKeySecret:
    description: 'api key secret for Twitter api'
    required: true
  accessToken:
    description: 'access token for Twitter api'
    required: true
  accessTokenSecret:
    description: 'access token secret for Twitter api'
    required: true
outputs:
  errorMessage:
    description: 'if something went wrong, the error message'
runs:
  using: docker
  image: Dockerfile
  args:
    - --message="${{ inputs.message }}"
    - --apiKey="${{ inputs.apiKey }}"
    - --apiKeySecret="${{ inputs.apiKeySecret }}"
    - --accessToken="${{ inputs.accessToken }}"
    - --accessTokenSecret="${{ inputs.accessTokenSecret }}"